version: "2"

services:

  redis:
    image: "redis:3.0-alpine"
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_USER=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: unbabel_app
    restart: always
    image: unbabel-app:latest
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    environment:
      - DATABASE_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CALLBACK_URL=https://webhook.site/0885f058-9372-4dd7-a8dd-f2d6e831c8e6
    command: uwsgi --ini /home/unbabel/config/application.ini
    ports:
      - "5000:5000"
  celery:
    container_name: unbabel_celery
    restart: always
    image: unbabel-app:latest
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    environment:
      - DATABASE_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CALLBACK_URL=https://webhook.site/0885f058-9372-4dd7-a8dd-f2d6e831c8e6
    command: celery worker --app=app -l info

volumes:
  redis:
  db-data: