"""empty message

Revision ID: a2bd3d6a7733
Revises: 
Create Date: 2018-12-24 00:27:00.480710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bd3d6a7733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('source_text', sa.String(length=256), nullable=False),
    sa.Column('translated_text', sa.String(length=1024), nullable=True),
    sa.Column('source_language', sa.String(length=2), nullable=False),
    sa.Column('target_language', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    # ### end Alembic commands ###
